//forced code, got to fix this. it solved the issue for me, but its not complete.
window.onload = function(){
    let ids = idList.split('\n');
    let id = '';

    for(let i = 0; i < ids.length; i++){
        let wordToCompare = ids[i];
        for(let j = 0; j < ids.length; j++){

            if(ids.indexOf(wordToCompare) !== ids.indexOf(ids[j])){

                let indexes = offByXCharacters(wordToCompare, ids[j]);
                if(indexes.length === 1){
                    console.log(indexes);
                    console.log(wordToCompare + '\n' + ids[j]);
                    id = wordToCompare.slice(indexes[0], indexes[0+1]); 
                    break;               
                }

            }

        }
    }
}

function offByXCharacters(id1, id2){
    let indexes = [];
    for(let i = 0; i < id1.length; i++) { 
        if(id1.charAt(i) !== id2.charAt(i)) {
            let chardiff = id1.charAt(i); 
            indexes.push(id1.indexOf(chardiff)); 
        }
    }
    return indexes;
}

let idList = `dghfbsyiznoumojleevappwqtr
dghfbsyiznoumkjljevacpmqer
dghfbbyizioumkjlxevacpwdtr
dghfbsesznoumkjlxevacpwqkr
dghfbsynznoumkjlxziacpwqtr
cghfbsyiznjumkjlxevacprqtr
dghfjsyizwoumkjlxevactwqtr
dghfdsyfinoumkjlxevacpwqtr
hghfbsyiznoumkjlxivacpwqtj
dgcfbsyiznoumkjlxevacbuqtr
dghfbsyiznoymnjlxevacpwvtr
dfhfbsyiznoumkulxevacptqtr
dghfasyiznovmkjlxevacpwqnr
dghfbsyihnouikjlxevackwqtr
dghfbayiznolmkjlyevacpwqtr
jghfbsyiznoumnjldevacpwqtr
dhhfbsyuznoumkjlxevakpwqtr
nehfrsyiznoumkjlxevacpwqtr
dghfbsyiznxdmkolxevacpwqtr
dgpfbsyizwlumkjlxevacpwqtr
yghfbsyiznoumkjlsevacpwqtm
dghfssyiznoumkjlxevvcpwqjr
dahfbsyiznoumkjlfevacpwqto
duhfcsyiznouvkjlxevacpwqtr
dghfbvyiznoumkjlrevacpwvtr
dghfgsyiznoumknlxgvacpwqtr
jghfbeyiznkumkjlxevacpwqtr
daofbsyiznoumkjlxevampwqtr
dghfbsyiznojmkjlxeracpcqtr
dghnbsyiznouokjlxevaclwqtr
dgifbsyiznoumkjlxevnspwqtr
dgkfpsziznoumkjlxevacpwqtr
dghfxsyijnoumkjlxevaccwqtr
dghfbsyiznolmkjlwevzcpwqtr
dkhfbsaiznoumkjlxevacpwqtg
dghfbsygknoumkjlaevacpwqtr
dghfbsyizizumkjlxevacpxqtr
ighfbbyijnoumxjlxevacpwqtr
dghfbsyizrouekjlxevacpwktr
dghobsyiznoujkjlxevacnwqtr
dghpbsyizyoumkjlxeaacpwqtr
dghffsyiznoymkjlxevacewqtr
dghkbssiznoumzjlxevacpwqtr
dghfbsyawnoumkjlxevacpwjtr
drhfbsyiznormkjlfevacpwqtr
dghfbsoiznouwkjlxevacpwqtn
dghfmsyiznoumkjlxlvecpwqtr
dxhfbsyiznoumkjlxeeacvwqtr
dghnbsyiznoumkjsxevacpwqur
dghfbsyiznrujkjlxevacpwqtc
dghfbstoznoumhjlxevacpwqtr
dghfboyiznzumkjlvevacpwqtr
dghfbsyiznjumkjlxevgcpwmtr
dghfbsnizaoumkjlxevacpwetr
dghfbsyirnoumkjoxevacplqtr
dghfbsyiznoumkjlxavvckwqtr
dghfbjdiznoumkjlxevacpwptr
dghfbsywznoumkjlxeiacpwqcr
djhfbsyizuoumkjlxelacpwqtr
dghffsniznoumkjlxpvacpwqtr
dghebsyizuoumkjlxevecpwqtr
rghfbsyiznourkjcxevacpwqtr
dghfbsyignoumkwlxenacpwqtr
dghfbsyiznrufkjlxevacpwqth
dgifbsyiznoumkjlxevacpjqnr
dghfbsyiznoumkjbxevaxpwqtw
dsufbsyizncumkjlxevacpwqtr
dihfbsyiznoumujlxecacpwqtr
dghfbiyiznoumkjlxevajpwqtn
dghqbsyixnoumkjlrevacpwqtr
dghfbsyiznouukjlxeuacpwqtx
dghfbsyizyoumksfxevacpwqtr
dghfbsiiznopfkjlxevacpwqtr
eghfbsyidnoumkjlxexacpwqtr
dghfbgyiznouwkjlwevacpwqtr
dghfbsyyznoumkjlxevacwwqtf
bghfbtypznoumkjlxevacpwqtr
dghfbsyiznoumtjlxebacpwetr
dghfbsgiznonmkplxevacpwqtr
dghfbsyiznoumxjlxevanpwqpr
dghfbsyiznwumujuxevacpwqtr
dghxbsyiznoumkjzxevaypwqtr
dghfbsyhznoumkjlxlvacpiqtr
dghfbsyiznoumkjlxevzcnwqrr
dvhfbsyiznoumkjluevacpzqtr
dghcbsyiznoumkjlxmvacpwetr
dghfbsyiznohmkjvxbvacpwqtr
dghfzsyiznouokjlxevacpwqpr
dghfbsyiznoumkjlxevachtqth
dghfbsyiznoumkjlxjvacpfutr
dghfbsyiznoumkjlxevsppwqtt
dghfusyiznouakhlxevacpwqtr
dghfbsyizcoumkjlxrvaipwqtr
dghebsyipnoumfjlxevacpwqtr
dgdfbsyiznoumkjlwevacpkqtr
dghfbsyiznoumkjlcffacpwqtr
dghfbsypznfumkjlxevacpwqar
dghfbsyiznojmkjlxevgcpkqtr
dghfbsyiznoumkjlaevlcpwstr
dgafrsyiunoumkjlxevacpwqtr
dghfbsyiznouqljlxevacrwqtr
dyhkbsyiznokmkjlxevacpwqtr
pghfbsciznoumkjlxevacpwvtr
dghfbxyiznonmkjllevacpwqtr
ighfbsyizxoumkjlxevacpzqtr
dgffbsyoznoumkjlxevacpwqto
hghfbsyiznoumkjlpevachwqtr
dlhfosyiznoumkjldevacpwqtr
dghfbsvizkoumkjlxvvacpwqtr
dbafbsyiznozmkjlxevacpwqtr
dghfbsyidnoumkjlxrvjcpwqtr
dghfbsyiznfumkjlxeqacpwqta
dghfbsfiznoumkjvxevacjwqtr
dghfbsyimnoumrjlhevacpwqtr
dghflsyiznoumkjlxevacpvqmr
dghfbmfiznoumkjlxevacpdqtr
dghfbsyizsouzkjlxevscpwqtr
dghfksyiznoumimlxevacpwqtr
dghfbsyiznoumkjlxevbwpwqur
wghcbsyiznoumkjlkevacpwqtr
kghfbioiznoumkjlxevacpwqtr
dghfbsiizeoumkjlxmvacpwqtr
dglfbsyilnoumkjlxevpcpwqtr
dgqfbsylznoumkjlxevacpwqcr
dglfhsyiznoumkjlxevacpwqdr
dghfbsymznoumkjlxbvacpwqtb
hghfbsyizhoumkjlxtvacpwqtr
dghdbsyiznoumkjlxeiacpyqtr
dohfbsyiznoumkjmxlvacpwqtr
xhhfbsyiznoumkjlxegacpwqtr
dlhfbsyiznoumkjlxnvahpwqtr
dghfbsyiznovdpjlxevacpwqtr
dgcfbsyiznoumkjlxevactwqdr
dghfksyiknoumkjlxevacpwqcr
ughfqsyiznoumkjlxevacpwctr
dghfbjyiznoumkjlxsvacnwqtr
dgwfbagiznoumkjlxevacpwqtr
dghfbsyiznoumknlxevtcpwqdr
jghfksyiznoumkjlxeoacpwqtr
dghfbsyiznoimkjlwezacpwqtr
dghfbsyiunoumkjlxeqacpwstr
dghfbsyizjoumkwlxevaypwqtr
dghfysriznoumkjlxevucpwqtr
dghfbsygzjoumkjfxevacpwqtr
dghfbhviznoumkjlxevacpwqtq
dghfbsyiznoumkjvwevacpwqur
dghfbsyiznoumtjlxevacplqnr
yghfbsysznouykjlxevacpwqtr
dgwfbsiiznoumkjlxevacfwqtr
dghfbsyizooumkjlxevampiqtr
dshfbsyiznoumkjlxevawpoqtr
dghtbsyxznuumkjlxevacpwqtr
dkhfblyiznoumkjlxevacpaqtr
dgkfbsyiinoumkjlxegacpwqtr
dghfbtxiznouhkjlxevacpwqtr
dghfbsyiznoumkjlxkvmcpeqtr
dghfbsyiznoumkjlghvacpwqmr
dghfbsbizioumkjlcevacpwqtr
dphfbsyizhoumkjwxevacpwqtr
dghfbsyiznqumkjlugvacpwqtr
dghfbsjinnoumkjlxevacpwetr
mghfbsyiznoumkjlxfvacpjqtr
dghfbsxiznoumkjlxetacwwqtr
dghmbsyiznoumbjlxevacpwqyr
dghfbsyiznwumkjlwevacmwqtr
dgkfbsyiznotmkjlxevacpwstr
dghfbsyiznouykjlxeiacuwqtr
dghfbsynznbhmkjlxevacpwqtr
dgyfbsyiznoumtjlbevacpwqtr
dghfbftiznoumkjlxevacpwatr
dghfvsyiznouikjlievacpwqtr
dghfbsyiznodmkjlxevncpwqtz
yfhfbsyiznoumkjluevacpwqtr
dghfbzyiznoumhflxevacpwqtr
dphfbsyizncumkjlxevacpwqtf
dghfasyiznoumkjlxeaicpwqtr
dgffbsyiznoumkjlzevacpwqsr
dghfbsyiznoumkmxxcvacpwqtr
dghffsyiznoumkjlxevacpwqre
dghfbsyizndmmkjlxemacpwqtr
dghfbsviznoamkjlxevappwqtr
dghfbsyiznouckrlxevacpdqtr
dgwfbsyiznyumkjlxevacpqqtr
dujfbsyiznoumgjlxevacpwqtr
dghobsailnoumkjlxevacpwqtr
dghfkqyiznoumknlxevacpwqtr
dghfbyypznoumkjlxevacpwatr
wqhfbsyiznoumkjlxevzcpwqtr
dghfbsyiznoumwjlxrvacppqtr
dghfbsymznoumkflxevacplqtr
dghfbsyiznounkjpgevacpwqtr
ighfbsyijnoumxjlxevacpwqtr
dghfbsyizroumkjllevncpwqtr
dghfbsliznokmkjlxevacpwqtb
dgefbsyiznoumkqlxevpcpwqtr
dghfbtypznouzkjlxevacpwqtr
dmhfbsyiznoumkjlxeyactwqtr
vohfbsyiznoumkjlqevacpwqtr
dgsfpsyiznodmkjlxevacpwqtr
dghfzsyijnoumkjnxevacpwqtr
dghfbayijroumkjlxevacpwqtr
dghfbsyiznodmxjlxgvacpwqtr
dghfbsyiznocmkjlxhvaipwqtr
dghmbsyignoumkjlxevacpoqtr
dghfbsyiznosmkjlncvacpwqtr
dggfbsyiznuumkjlxevacpwqrr
dghibsyilnoumkjlxevacowqtr
dghfbsyiznoumkjluevbcowqtr
dghfbsaiznyuvkjlxevacpwqtr
dgnfxsyiznommkjlxevacpwqtr
dghfbnyiznoumkjlsnvacpwqtr
dghfssiiznoumkjlxavacpwqtr
dghfbsyizneumajlxevacfwqtr
dghfbsyiznoumkjlxevycpvptr
qghfbsyizgoumkjlxevacpwttr
vghfbsyiznoumkjlievaepwqtr
dghfbsyiznoumejlxjvacpwdtr
dghfbsyispoumkjlxevacpwqtg
duhfbsyizpoumkjlxenacpwqtr
dghfbsyifnoumkblxevacpnqtr
bghfbsyxznoumkjleevacpwqtr
dgtfbsyzpnoumkjlxevacpwqtr
dghfbsyiznoumkjlsecacpwqth
dghfqsyiznjumkjlxevawpwqtr
dgcfbsyizboumkjlxevacqwqtr
dghfbqyiznoumkjkxevacpwqtj
dgyfbsyfznoumkjlievacpwqtr
dghfdsyiznoumkplxevacpwdtr
dphfbsyuznkumkjlxevacpwqtr
dghfbsyiznoupkjitevacpwqtr
dghfisyiznoamkjlxevacpwqwr
dgufbsyiznoumkjlxivvcpwqtr
dghfbvyiznoumkjlxevacvwqtz
dghfbsyiqnxumkjlxbvacpwqtr
dghubsyiznqumkflxevacpwqtr
dghfbsyiznzumkjlxevacpdbtr
dghfbsyiznoumkjlxehacpwwrr
mghfbsyiznoumkjlxevacpwqbp
dvhfbryiznoumkclxevacpwqtr
dghbbsyiznotmkjlxevacpwqhr
dghfrsyiznoomkjlxevacpwqto
dghfbkyiznoumkjlxeracpxqtr
dghfbfyizfoumkjlxevacpwjtr
dghfbsyizqoulkjlxevacpwqtt
dghfbsyiwnoumkjlxevacxwgtr
dghfbsyiznormkjlgxvacpwqtr
dghybsyizioumkjoxevacpwqtr
dchfbsyiznoumkjlxyvacpwqtc
dgyfbsyiznouckjlxewacpwqtr
dakfbsyeznoumkjlxevacpwqtr`;